# https://developers.home-assistant.io/docs/apps/configuration#app-dockerfile
FROM ledfxorg/ledfx:latest

LABEL org.opencontainers.image.title="Home Assistant App: LedFx"
LABEL org.opencontainers.image.description="LedFx app for Home Assistant OS"
LABEL org.opencontainers.image.source="https://github.com/LedFx/LedFx"
